name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '42 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://westseattleblog.com/\?plugin\=all-in-one-event-calendar\&controller\=ai1ec_exporter_controller\&action\=export_events\&no_html\=true -o wsb-nohtml.ical
        curl https://westseattleblog.com/\?plugin\=all-in-one-event-calendar\&controller\=ai1ec_exporter_controller\&action\=export_events -o wsb.ical
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push